version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/web
        depends_on:
            - sqlite
    redis:
        image: sqlite
